name: CI

on:
  schedule:
    - cron: "*/10 * * * *"  # 10分ごとに実行
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "SMTP_HOST=${{ secrets.SMTP_HOST }}" >> $GITHUB_ENV
        echo "SMTP_PORT=${{ secrets.SMTP_PORT }}" >> $GITHUB_ENV
        echo "SMTP_USERNAME=${{ secrets.SMTP_USERNAME }}" >> $GITHUB_ENV
        echo "SMTP_PASSWORD=${{ secrets.SMTP_PASSWORD }}" >> $GITHUB_ENV
        echo "TO_EMAILS=${{ secrets.TO_EMAILS }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget gnupg
        wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
        echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" | sudo tee /etc/apt/sources.list.d/google-chrome.list
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable
        sudo apt-get install -y python3-pip
        pip3 install selenium beautifulsoup4 jpholiday python-dotenv

    - name: Set up ChromeDriver
      run: |
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+' | head -n1)
        DRIVER_VERSION=$(curl -sS "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        wget -N "https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip"
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/
        rm chromedriver_linux64.zip
        echo "PATH=\$PATH:/usr/local/bin" >> $GITHUB_ENV

    - name: Check Chrome and ChromeDriver versions
      run: |
        google-chrome --version
        chromedriver --version

    - name: Ensure correct file path
      run: |
        echo "Current working directory: $(pwd)"
        echo "Available files in $(pwd):"
        ls -lah

    - name: Run your application
      run: |
        if [ -f "test2.py" ]; then
          python3 test2.py
        else
          echo "test2.py does not exist in the current directory"
          exit 1
        fi

    - name: Upload debug logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: debug-logs
        path: test_debug.log
